# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-07-27 15:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Favory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('id_voisin', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Voisin',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, null=True)),
                ('phone', models.CharField(max_length=100, null=True)),
                ('adress', models.CharField(max_length=100, null=True)),
                ('about', models.TextField(null=True)),
            ],
        ),
        migrations.AddField(
            model_name='favory',
            name='Favory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Voisin'),
        ),
    ]
